### ISSUE TITLE
tokenization with extra space

### ISSUE THREAD

**Issue by FjjDessoyCaraballo** [FjjDessoyCaraballo/minishell#1]
At the end of the tokenizing, there seems to be an extra space being splitted into the array/linked list. This could lead into problems later.

**Comment by Torutu** [comment]
show me what kind of test you did so I can work around that and anything related to it, you can add pictures or screenshots to show me how it looks like for you

**Comment by FjjDessoyCaraballo** [comment]
Thanks for reminding me of the input. I tried with many inputs, and the behavior persists:

![Screenshot from 2024-07-10 11-22-44](https://github.com/FjjDessoyCaraballo/minishell/assets/63795029/431dcc1b-fe15-4e04-bd36-18141f54fc6c)
![Screenshot from 2024-07-10 11-24-58](https://github.com/FjjDessoyCaraballo/minishell/assets/63795029/9a996ef8-452e-48be-b311-39064d7e40fe)

The string is ending with spaces (multiple and single) and the last unknown command always returns one extra space.

**Comment by Torutu** [comment]
check now and please confirm and close if it works as it should 😃
![image](https://github.com/FjjDessoyCaraballo/minishell/assets/120149333/0949fd9e-b6a4-4621-aed9-8463211436e3)
first input "       "
second input "cd"
third input "cd       "
(there should be a better way to show that we actually added spaces to these inputs 😅)
