### ISSUE TITLE
echo only prints new line

### ISSUE THREAD

**Issue by Torutu** [FjjDessoyCaraballo/minishell#11]
echo not working and only prints new line

![image](https://github.com/user-attachments/assets/9596d3ac-c420-40e6-b5a2-97c1faca6fa9)

**Comment by FjjDessoyCaraballo** [comment]
I fixed the issue, but now there is a secondary problem: inputting echo -n with no space within flag and string still prints only the string with no newline.

[I can't believe this is not shell] echo -naslkjdaljdnawld // notice this line
token value:[echo]
token type:[0]
id:[0]
token value:[-naslkjdaljdnawld]
token type:[404]
id:[1]
slkjdaljdnawld[I can't believe this is not shell]

**Comment by Torutu** [comment]
![image](https://github.com/user-attachments/assets/6cb639c8-3a16-4650-bed5-44237932ce8d)
not sure if helps but my token already checks if echo has a flag -n or not
token->value = "-n";
token->type = FLAG;
could help with the yodeling function
