### ISSUE TITLE
Parsing out commands (single commands)

### ISSUE THREAD

**Issue by FjjDessoyCaraballo** [FjjDessoyCaraballo/minishell#12]
We need to filter and parse out the executables for simple execution (single commands, and maybe piping later). Below you will find the pseudo-code that we elaborated to parse it out for the tokenizer:

```c
char *loop_path_for_binary(char **paths) // idk what parameters you will want
{
	//join path + '/' + executable
	//NB: use ft_strsjoin(s1, s2, separator)
	char	*token_for_binary;
	char	*token_with_path;
	int		i;

	i = 0;
	while (paths[i])
	{
		token_with_path = ft_strsjoin(paths[i], token_for_binary, "/");	
		if (!access(token_with_path, F_OK))
		{
			if (!access(token_with_path, X_OK))
				return (token_with_path);
			else
				return (NULL);
		}
		i++;
	}
	return (NULL);
}

**Comment by Torutu** [comment]
so far this is what I manage to do, I can clean it down so that the value is only "ls" and not "/usr/bin/grep"

![image](https://github.com/user-attachments/assets/233f6bf7-1c19-4ea8-87e4-f6b20b2a6538)

**Comment by FjjDessoyCaraballo** [comment]
That's the idea. We cycle through the possible paths to know exactly where to find to use with execve().

https://man7.org/linux/man-pages/man2/execve.2.html

**Comment by FjjDessoyCaraballo** [comment]
Closing this issue: parsing has been done in pull request #20 by @Torutu
