### ISSUE TITLE
export not updating without arguments

### ISSUE THREAD

**Issue by FjjDessoyCaraballo** [FjjDessoyCaraballo/minishell#13]
Export is updating the environment, but is not updating the enviroment that gets printed when you input just 'export'.

e.g.:
%> export
{ env list with "declare -x KEY="value"}

**Comment by Ginger-Leo** [comment]
just impliamented export to print alphabetically, will submit pull request now. also alot of norminetting done x

**Comment by Ginger-Leo** [comment]
Closing issue after fix in commit [84d5216](https://github.com/FjjDessoyCaraballo/minishell/commit/84d521681fe541ca37f35869c9dcbb3baa66c64c)

**Comment by FjjDessoyCaraballo** [comment]
With recent updates, export has stopped working. Same issue, same problem, but I don't have a lead as to why this is happening now.

**Comment by Ginger-Leo** [comment]
We are not even getting into the export function....

**Comment by Ginger-Leo** [comment]
Export working correctly with and without args. printing alphabetically
