### ISSUE TITLE
Empty processes for piping

### ISSUE THREAD

**Issue by FjjDessoyCaraballo** [FjjDessoyCaraballo/minishell#19]
Problem: between pipes there should ALWAYS be some instructions. If no instructions are given between pipes, we print: " bash: syntax error near unexpected token '|' "

Solution: since we are working with a linked list, we could just check if the previous and/or next thing to the pipe exists or not. If its another pipe, we return with error code 2. (yes, we have to return with this specific return code) When returning with this code, make sure to overwrite our status variable inside the data struct (e.g. data->status = return code)

![image](https://github.com/user-attachments/assets/0c090f70-e60c-415a-9c2e-f9b25a2db8c1)

**Comment by FjjDessoyCaraballo** [comment]
Some other cases for parsing

![image](https://github.com/user-attachments/assets/c43df224-2f5e-4ca8-b09c-93dcbeb3606f)

**Comment by FjjDessoyCaraballo** [comment]
The fix is working partially after merge #29 :

![image](https://github.com/user-attachments/assets/2a98fc8b-f14c-4485-86b7-a01f2bc5fdfd)

We need to be more assured that this stuff will not happen, because at my end I am highly assuming that parsing has taken away most of the edge cases.

**Comment by Ginger-Leo** [comment]
tokenizer line 68 s causing a segfault when you put  "|", because its looking at the 'previous' token and there isnt one.

**Comment by FjjDessoyCaraballo** [comment]
![image](https://github.com/user-attachments/assets/5f97c55a-8983-4b7c-95d2-e16f296ef1f3)

Closing issue: fix made by pull request #34
