### ISSUE TITLE
unset with expansion clear almost all

### ISSUE THREAD

**Issue by FjjDessoyCaraballo** [FjjDessoyCaraballo/minishell#53]
Unset seems to work without expansion, but when an expansion is used, the whole env_ll is broken. 

![image](https://github.com/user-attachments/assets/3d72f805-ac05-4f24-8c33-913e7ffb2eba)

**Comment by Ginger-Leo** [comment]
this has now developed a different fault. it now doesnt print the newly added values,  value....

export XBOX=564;

XBOX=

**Comment by Ginger-Leo** [comment]
this is not  a problem anymore, I think Waled sorted it in  the end.
