### ISSUE TITLE
CD is taking too many arguments

### ISSUE THREAD

**Issue by FjjDessoyCaraballo** [FjjDessoyCaraballo/minishell#54]
CD is working with more arguments than it should. In this scenario I've tested with stuff after cd and it should not execute if anything is given after the first parameter.

![image](https://github.com/user-attachments/assets/71adc587-1fca-42e6-b595-42375d639254)

**Comment by Ginger-Leo** [comment]
I think this is sorted now.

added a simple change to the token->next->value

**Comment by Ginger-Leo** [comment]
will push changes into main x
