### ISSUE TITLE
redirection isn't parsed correctly with fds

### ISSUE THREAD

**Issue by FjjDessoyCaraballo** [FjjDessoyCaraballo/minishell#64]
Redirection is being incorporated to the argument. Bash takes the redirection as something separate from the fd in this case.

In simple words:

when argument has a "<", ">", "<<", or ">>"  (third image)

![image](https://github.com/user-attachments/assets/a0acb715-0a05-4238-b48a-16fbc11c0775)

![image](https://github.com/user-attachments/assets/9bb3e9d3-489f-4279-b472-1ffbfbe5f6a9)

![image](https://github.com/user-attachments/assets/dd92c1c4-b78a-4689-9e27-f2e33d574914)

**Comment by Torutu** [comment]
![image](https://github.com/user-attachments/assets/812a57e7-7bc0-478a-80bc-70ff27bc459d)

it should work already if you merged my updates.
do you have the file src/parse/modify_str.c? it should add spaces when it finds | > < >> << to tokenize and parse correctly
