### ISSUE TITLE
When ran the Ctrl + 'D' command from school PC, this popped up

### ISSUE THREAD

**Issue by BrunoPosa** [FjjDessoyCaraballo/minishell#67]
![image](https://github.com/user-attachments/assets/26330599-2fab-4ec3-b33a-44a380a1cba0)

**Comment by BrunoPosa** [comment]
Similar in bash 
![image](https://github.com/user-attachments/assets/e554ebf2-0bed-4ec0-9065-dd9693c31a26)

**Comment by FjjDessoyCaraballo** [comment]
Run the code with `-fsanitize=address` and kt should point you to the segfault. Probably due to freeing unused pointers, but I can't know with the available information.

**Comment by FjjDessoyCaraballo** [comment]
Closing issue: fix in commit b2b8bebcb85f80c690d1192ca439eb16cfe68eb7
