### ISSUE TITLE
Norm and formatting

### ISSUE THREAD

**Issue by BrunoPosa** [FjjDessoyCaraballo/minishell#68]
Last chore before submitting to vogsphere - Ensure the 42header authors are correct

**Comment by BrunoPosa** [comment]
single_q(), doubleq(),  handle_env_variable() have 5 args instead of 4
 ![image](https://github.com/user-attachments/assets/a5fc0772-a299-4170-acc1-15a1febebe89)

**Comment by BrunoPosa** [comment]
single_q(), doubleq(),  handle_env_variable() have 5 args instead of 4
 ![image](https://github.com/user-attachments/assets/a5fc0772-a299-4170-acc1-15a1febebe89)

**Comment by FjjDessoyCaraballo** [comment]
Closing issue: formatting done since commit 58b08b1f352fa771898701a5495f81d81f2a514c
