### ISSUE TITLE
taking '>' as arguments and not redirections

### ISSUE THREAD

**Issue by Torutu** [FjjDessoyCaraballo/minishell#76]
![image](https://github.com/user-attachments/assets/09f8808e-b52d-4ebb-8994-28e64be6a326)
![image](https://github.com/user-attachments/assets/5431e918-3df0-4f66-80c5-7a5a2fa639f4)

it is still treated as a redirection, I know it changes to array in execution so it looses some attributes, I can try to work on it by comparing the token index to the array index
so if token index 2 is argument and in array index 2 we find < then it will be treated as an argument and not redirection

in some cases we could have a file named '>' and we need to treat it as an argument if someone feeling silly and wants to cat '>' '>>' "<<" ...

**Comment by FjjDessoyCaraballo** [comment]
Closing issue: issue has been taken care by commit 3020a8f0a041326a35232efe3e053e1e7ee36687
